config/routes.rb
Rails.application.routes.draw do
  get 'video/:id', to: 'video#show', as: :video
  get 'video/iframe/:id', to: 'video#iframe'
  get 'video/code/:id', to: 'video#code'
  get 'video/preview/:id', to: 'video#preview'
  get 'video_paths', to: 'video#path' 
  get 'home/index'
  root 'home#index'
  devise_for :accounts, controllers: {registrations: "user/registrations", sessions: 'user/sessions', passwords: 'user/passwords', omniauth_callbacks: "user/omniauth_callbacks"}

  resources :notifications
  resources :avatars, only: [:create, :new]
  namespace :admin do
    get '/' => 'admin#index'
    resources :users, :only => :index
  end
  resources :transcoding_strategy_relationships
  resources :tags_relationships
  resources :tags
  resources :transcoding_strategies
  resources :transcodings
  resources :water_mark_templates do
    member do
      patch :enable
      patch :stop
    end
  end
  namespace :advertise do
    resources :strategies
  end
  namespace :advertise do
    resources :resources
  end
  resources :players
  resources :logos

  resources :users do
    resource :space_stat, :only => [:show], :controller => 'statistics/space_stat'
  end
  resources :companies, :controller => 'company/companies' do
    member do
      patch 'activate'
      patch 'inactivate'
    end
    resources :members, :controller => 'company/members' do
      member do
        patch 'upgrade'
        patch 'downgrade'
        patch 'activate'
        patch 'inactivate'
      end
    end
  end

  resources :video_products do
    member do
      get 'download'
    end
  end
  resources :video_product_groups do
    member do
      get 'download'
      patch 'clip'
      get 'last'
    end
    resource :user_video, :only => [] do
      get 'clip_existed'
    end
  end
  resources :video_product_group_check_statuses
  resources :user_videos, :except => [:create] do
    member do
      post 'republish'
      get 'clip'
    end
    collection do
      post :preupload, :controller => :uploader
      post :upload, :controller => :uploader
      get 'muti_uploads'
      get 'get_token'
      post 'uploads'
    end
  end
  resources :video_lists

end

app/models/privilege/video_list.rb
module Privilege
  module VideoListWithPrivilege
    def self.included(base)
      base.class_eval do
        scope :visible, ->(user) do
          if user.company_member?
            joins(:video_list_privileges, :owner).where(
                :owner => user.owner,
                :video_list_privileges => {:user_id => user})
          else
            where(:owner => user.owner)
          end
        end
        scope :uploadable, ->(user) do
          if user.company_member?
            visible(user).where(:video_list_privileges => {:can_upload => true})
          else
            visible(user)
          end
        end
      end
    end
  end
end

app/models/video_list.rb
class VideoList < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User'
  has_many :video_list_links
  has_many :user_videos, :through => :video_list_links
  has_many :video_product_group_list_links
  has_many :video_product_groups, :through => :video_product_group_list_links
  has_many :video_list_privileges, :dependent => :delete_all
  has_many :privilege_members, :through => :video_list_privileges, :source => 'user'
  include Privilege

  def set_privileges(privileges)
    transaction do
      member_ids = privileges.values.reduce { |s, ids| s | ids } || []
      exist_member_ids = []
      self.video_list_privileges.each do |privilege|
        user_id = privilege.user_id
        if member_ids.exclude? user_id
          privilege.destroy
        else
          exist_member_ids.append user_id
          privilege.update_privileges!(privileges)
        end
      end
      (member_ids - exist_member_ids).each do |member_id|
        privilege = VideoListPrivilege.new(:video_list => self, :user_id => member_id)
        privilege.update_privileges!(privileges)
      end
    end
  end
end

#------------------------------------------------------------------------------
# VideoList
#
# Name       SQL Type             Null    Default Primary
# ---------- -------------------- ------- ------- -------
# id         int(11)              false           true   
# name       varchar(255)         true            false  
# owner_id   int(11)              true            false  
# created_at datetime             false           false  
# updated_at datetime             false           false  
#
#------------------------------------------------------------------------------

app/controllers/video_lists_controller.rb
class VideoListsController < ApplicationController
  before_action :authenticate_account!, :check_login
  before_action :set_new_video_list, only: [:index, :show]
  before_action :set_video_lists, only: [:index, :show, :create]
  before_action :set_video_list, except: [:index, :create]
  before_action :set_nolist_user_videos, only: [:show]

  def index
  end

  def edit
    @privilege_users = Hash[@video_list.video_list_privileges.map { |privilege| [privilege.user, privilege] }]
    @privileges = Settings.video_privilege.keys
  end

  def update
    @video_list.transaction do
      @video_list.name = video_list_params[:name]
      @video_list.save!
      privileges = video_list_params[:privilege] || {}
      privileges.each do |_, members|
        members.map! { |i| i.to_i }
      end
      @video_list.set_privileges(privileges)
      redirect_to @video_list
    end
  end

  def show
    render :index
  end

  def create
    @video_list = VideoList.new(new_video_list_params)
    @video_list.owner = current_user

    if @video_list.save
      redirect_to @video_list, notice: 'New List is successfully created.'
    else
      render :index
    end
  end

  def update_user_video_on
    redirect_to @video_list
  end

  private

  def set_video_lists
    @video_lists = VideoList.where(:owner => current_user.owner)
  end

  def set_video_list
    @video_list = VideoList.find params[:id]
  end

  def set_new_video_list
    @new_video_list = VideoList.new
  end

  def set_nolist_user_videos
    @nolist_user_videos = UserVideo
                              .where(:owner => current_user)
                              .joins('LEFT JOIN video_list_links ON user_videos.id=video_list_links.user_video_id')
                              .where(:video_list_links => {:id => nil})
  end

  def video_list_params
    params.require(:video_list).permit(:name, :privilege => [Hash[Settings.video_privilege.keys.map { |k| [k, []] }]])
  end

  def new_video_list_params
    params.require(:video_list).permit(:name)
  end
end

app/helpers/video_lists_helper.rb
module VideoListsHelper
  def has_video_privilege(privilege_users, member, privilege)
    return false if privilege_users.exclude? member
    privilege_users[member]["can_#{privilege}"]
  end
end

app/views/video_lists/_add_user_videos_form.html.erb
<h3>往分类中添加</h3>
<span>未分类的视频</span>
<%= form_for @video_list do |f| %>
    <table>
      <tr>
        <th>视频名称</th>
        <th>操作</th>
      </tr>
      <% @nolist_user_videos.each do |uv| %>
          <tr>
            <td><%= link_to uv.video_name, user_video_path(uv) %></td>
            <td><% 
            # link_to '添加', video_list_user_video_path(@video_list, uv), :method => :put 
            %></td>
          </tr>
      <% end %>
    </table>
<% end %>

app/views/video_lists/_form.html.erb
<%= form_for(@video_list) do |f| %>
    <% if @video_list.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@video_list.errors.count, "error") %> prohibited this video_list from being saved:</h2>

          <ul>
            <% @video_list.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <table>
      <tr>
        <th></th>
        <% @privileges.each do |privilege| %>
            <th><%= Settings.video_privilege[privilege] %></th>
        <% end %>
      </tr>
      <% current_user.company.members.company_members.active.each do |member| %>
          <tr>
            <td><%= member.nickname %></td>
            <% @privileges.each do |privilege| %>
                <td>
                <%= f.check_box "privilege[#{privilege}]", {:multiple => true, :checked => has_video_privilege(@privilege_users, member, privilege)}, member.id, nil %>
                </td>
            <% end %>
          </tr>
      <% end %>
    </table>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/video_lists/_index_form.html.erb
<table>
  <thead>
  <tr>
    <th>列表</th>
    <th colspan="2">操作</th>
  </tr>
  </thead>

  <tbody>
  <% @video_lists.each do |video_list| %>
      <tr>
        <td><%= link_to video_list.name, video_list %></td>
        <td><%= link_to 'Edit', edit_video_list_path(video_list) %></td>
        <td><%= link_to 'Destroy', video_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/video_lists/_new_form.html.erb
<%= form_for(@new_video_list) do |f| %>
    <span>添加</span>
    <div class="field">
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/video_lists/_show_user_videos_form.html.erb
<table>
  <tr>
    <th>视频名称</th>
    <th>操作</th>
  </tr>
  <% @video_list.user_videos.each do |uv| %>
      <tr>
        <td><%= link_to uv.video_name, user_video_path(uv) %></td>
        <td><%= link_to '移除', video_list_user_video_path(@video_list, uv), :method => :delete %></td>
      </tr>
  <% end %>
</table>

app/views/video_lists/_show_video_product_groups_form.html.erb
<table>
  <tr>
    <th>成品名称</th>
  </tr>
  <% @video_list.video_product_groups.each do |g| %>
      <tr>
        <td><%= link_to g.name, video_product_group_path(g) %></td>
      </tr>
  <% end %>
</table>

app/views/video_lists/edit.html.erb
<%= render 'user_videos/nav' %>
<h1>VideoLists#edit</h1>
<p>Find me in app/views/video_lists/edit.html.erb</p>

<%= render 'form' %>

app/views/video_lists/index.html.erb
<%= render 'user_videos/nav' %>
<h1>VideoLists</h1>

<%= render 'index_form' %>
<br>
<%= render 'new_form' %>

<% if @video_list %>
    <br>
    <h4><%= @video_list.name %></h4>
    <%= render 'show_user_videos_form' %>
    <%= render 'show_video_product_groups_form' %>
    <br>
    <%= render 'add_user_videos_form' %>
<% end %>