config/routes.rb
Rails.application.routes.draw do
  get 'video/:id', to: 'video#show', as: :video
  get 'video/iframe/:id', to: 'video#iframe'
  get 'video/code/:id', to: 'video#code'
  get 'video/preview/:id', to: 'video#preview'
  get 'video_paths', to: 'video#path' 
  get 'home/index'
  root 'home#index'
  devise_for :accounts, controllers: {registrations: "user/registrations", sessions: 'user/sessions', passwords: 'user/passwords', omniauth_callbacks: "user/omniauth_callbacks"}

  resources :notifications
  resources :avatars, only: [:create, :new]
  namespace :admin do
    get '/' => 'admin#index'
    resources :users, :only => :index
  end
  resources :transcoding_strategy_relationships
  resources :tags_relationships
  resources :tags
  resources :transcoding_strategies
  resources :transcodings
  resources :water_mark_templates do
    member do
      patch :enable
      patch :stop
    end
  end
  namespace :advertise do
    resources :strategies
  end
  namespace :advertise do
    resources :resources
  end
  resources :players
  resources :logos

  resources :users do
    resource :space_stat, :only => [:show], :controller => 'statistics/space_stat'
  end
  resources :companies, :controller => 'company/companies' do
    member do
      patch 'activate'
      patch 'inactivate'
    end
    resources :members, :controller => 'company/members' do
      member do
        patch 'upgrade'
        patch 'downgrade'
        patch 'activate'
        patch 'inactivate'
      end
    end
  end

  resources :video_products do
    member do
      get 'download'
    end
  end
  resources :video_product_groups do
    member do
      get 'download'
      patch 'clip'
      get 'last'
    end
    resource :user_video, :only => [] do
      get 'clip_existed'
    end
  end
  resources :video_product_group_check_statuses
  resources :user_videos, :except => [:create] do
    member do
      post 'republish'
      get 'clip'
    end
    collection do
      post :preupload, :controller => :uploader
      post :upload, :controller => :uploader
      get 'muti_uploads'
      get 'get_token'
      post 'uploads'
    end
  end
  resources :video_lists

end

app/views/admin/_nav.html.erb
<nav class="nav-secondary">
  <ul class="clearfix">
    <li class=""><a href="<%= admin_users_path %>"><i class="fa fa-fw fa-square"></i>用户管理</a></li>
    <li><a href="javascript:void();"><i class="fa fa-fw fa-square"></i>权限管理</a></li>
    <li><a href="javascript:void();"><i class="fa fa-fw fa-square"></i>API管理</a></li>
    <li><a href="javascript:void();"><i class="fa fa-fw fa-square"></i>操作日志</a></li>
    <% if can? :check, VideoProductGroup %>
    <li><a href="<%= video_product_group_check_statuses_path %>"><i class="fa fa-fw fa-square"></i>视频审核</a></li>
    <% end %>
    <% if can? :access, :company_account %>
    <li><a href="<%= companies_path %>"><i class="fa fa-fw fa-square"></i>企业管理</a></li>
    <% end %>
    <% if can? :access, :own_company %>
    <li><a href="<%= company_path(current_user.company)  %>"><i class="fa fa-fw fa-square"></i>企业账户</a></li>
    <% end %>
  </ul>
</nav>