config/routes.rb
Rails.application.routes.draw do
  get 'video/:id', to: 'video#show', as: :video
  get 'video/iframe/:id', to: 'video#iframe'
  get 'video/code/:id', to: 'video#code'
  get 'video/preview/:id', to: 'video#preview'
  get 'video_paths', to: 'video#path' 
  get 'home/index'
  root 'home#index'
  devise_for :accounts, controllers: {registrations: "user/registrations", sessions: 'user/sessions', passwords: 'user/passwords', omniauth_callbacks: "user/omniauth_callbacks"}

  resources :notifications
  resources :avatars, only: [:create, :new]
  namespace :admin do
    get '/' => 'admin#index'
    resources :users, :only => :index
  end
  resources :transcoding_strategy_relationships
  resources :tags_relationships
  resources :tags
  resources :transcoding_strategies
  resources :transcodings
  resources :water_mark_templates do
    member do
      patch :enable
      patch :stop
    end
  end
  namespace :advertise do
    resources :strategies
  end
  namespace :advertise do
    resources :resources
  end
  resources :players
  resources :logos

  resources :users do
    resource :space_stat, :only => [:show], :controller => 'statistics/space_stat'
  end
  resources :companies, :controller => 'company/companies' do
    member do
      patch 'activate'
      patch 'inactivate'
    end
    resources :members, :controller => 'company/members' do
      member do
        patch 'upgrade'
        patch 'downgrade'
        patch 'activate'
        patch 'inactivate'
      end
    end
  end

  resources :video_products do
    member do
      get 'download'
    end
  end
  resources :video_product_groups do
    member do
      get 'download'
      patch 'clip'
      get 'last'
    end
    resource :user_video, :only => [] do
      get 'clip_existed'
    end
  end
  resources :video_product_group_check_statuses
  resources :user_videos, :except => [:create] do
    member do
      post 'republish'
      get 'clip'
    end
    collection do
      post :preupload, :controller => :uploader
      post :upload, :controller => :uploader
      get 'muti_uploads'
      get 'get_token'
      post 'uploads'
    end
  end
  resources :video_lists

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User', :foreign_key => 'user_id'
  belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
  belongs_to :logo
  validates :name, presence: true
  include Privilege
end

#------------------------------------------------------------------------------
# Player
#
# Name          SQL Type             Null    Default Primary
# ------------- -------------------- ------- ------- -------
# id            int(11)              false           true   
# name          varchar(255)         true            false  
# user_id       int(11)              true            false  
# color         varchar(255)         true            false  
# logo_id       int(11)              true            false  
# logo_position varchar(255)         true            false  
# autoplay      tinyint(1)           true            false  
# share         tinyint(1)           true            false  
# full_screen   tinyint(1)           true            false  
# width         int(11)              true            false  
# height        int(11)              true            false  
# data          text                 true            false  
# created_at    datetime             false           false  
# updated_at    datetime             false           false  
# creator_id        int(11)              true            false  
#
#------------------------------------------------------------------------------

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_account!, except: [:show] # 匿名用户也可以加载播放器设置
  before_action :set_user_id, only: [:create, :update]
  before_action :set_player, only: [:edit, :update, :destroy]
  before_action :set_public_player, only: [:show]

  def index
    @players = Player.visible(current_user).page(params[:page])
  end

  def show
    if @player.logo
      case @player.logo_position
        when 'top_left'
          xpos = 0
          ypos = 0
        when 'bottom_right'
          xpos = 100
          ypos = 100
        when 'bottom_left'
          xpos = 0
          ypos = 100
        when 'top_right'
          xpos = 100
          ypos = 0
      end
      hash_water = {
          # file: @player.logo.uri_url(:normal) ,
          xpos: xpos,
          ypos: ypos,
          xrepeat: 0,
          opacity: 0.5
      }
      hash_water[:file] = @player.logo.uri_url(:normal) if not Rails.env.test?
    end

    respond_to do |format|
      format.html
      format.json {
        json_data = {
            init: {
                controls: true,
                preload: 'meta',
                autoplay: @player.autoplay ? @player.autoplay : false,
                width: @player.width ? @player.width : 852,
                height: @player.height ? @player.height : 480,
            },
            # logo: hash_water
        }
        json_data[:logo] = hash_water if @player.logo
        render json: json_data
      }
    end
  end

  def new
    @player = Player.new
    @player.autoplay = false
    @logos = {}
    logos = Logo.visible(current_user)
    logos.each do |logo|
      @logos[logo.name] = logo.id
    end
  end

  def edit
    @logos = {}
    logos = Logo.visible(current_user)
    logos.each do |logo|
      @logos[logo.name] = logo.id
    end
  end

  def create
    @player = Player.new(player_params)
    @player.creator = current_user

    respond_to do |format|
      if @player.save
        format.html { redirect_to action: "index", notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_player
    if params[:id] == '0'
      @player = Player.new(Settings.default_player.to_h)
    else
      @player = Player.visible(current_user).find(params[:id])
    end
  end

  def set_public_player
    if params[:id] == '0'
      @player = Player.new(Settings.default_player.to_h)
    else
      @player = Player.find(params[:id])
    end
  end

  def player_params
    params.require(:player).permit(:name, :user_id, :color, :logo_id, :logo_position, :autoplay, :share, :full_screen, :width, :height, :whitelist)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<% style 'lib/videojs/video-js' %>
<% style 'lib/videojs/videojs.watermark' %>
<% javascript 'lib/videojs/video.min' %>
<% javascript 'lib/videojs/videojs.watermark' %>
<script>
videojs.options.flash.swf = "/player1/video-js.swf";
</script>
<div class="panel-content">
    <%= form_for(@player, html: {class: "form-horizontal"}) do |f| %>
        <% if @player.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

                <ul>
                    <% @player.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <div class="row">
            <div class="cols large-6">
                <div class="row form-title">
                    <div class="cols large-4 l-text-right"><%= t controller.action_name %>播放器</div>
                </div>
                <div class="row">
                    <div class="cols large-4 l-text-right">
                        <label for="player-name">播放器名称:</label>
                    </div>
                    <div class="cols large-8">
                        <%= f.text_field :name, class: 'ntrol' %>
                    </div>
                </div>
                <div class="row">
                    <div class="cols large-4 l-text-right">
                        <label for="player-name">播放器颜色:</label>
                    </div>
                    <div class="cols large-8">
                        <label class="radio-inline">
                            <%= check_box_tag("player", "color", "black", :checked => true) %> 黑色
                        </label>
                        <label class="radio-inline">
                            <%= check_box_tag("player", "color", "classical") %> 经典
                        </label>
                        <label class="radio-inline">
                            <%= check_box_tag("player", "color", "other") %> 其它
                        </label>
                    </div>
                </div>
                <div class="row">
                    <div class="cols large-4 l-text-right">
                        <label for="player-name">LOGO:</label>
                    </div>
                    <div class="cols large-8">
                        <%= f.select :logo_id, @logos, {}, {:class => 'form-control'} %>
                    </div>
                </div>
                <div class="row">
                    <div class="cols large-4 l-text-right">
                        <label for="player-name">LOGO的位置:</label>
                    </div>
                    <div class="cols large-8">
                        <%= f.select :logo_position, {
                            '右上角' => :top_right,
                            '左上角' => :top_left,
                            '右下角' => :bottom_right,
                            '左下角' => :bottom_left
                        }, {}, {:class => 'form-control'} %>          
                </div>
            </div>        
            <div class="row">
                <div class="cols large-4 l-text-right">
                    <label for="player-name">自动播放:</label>
                </div>
                <div class="cols large-8">
                    <%= f.check_box :autoplay %>

                </div>
            </div>    
            <div class="row">
                <div class="cols large-4 l-text-right">
                    <label for="player-name">分享功能:</label>
                </div>
                <div class="cols large-8">
                    <%= f.select :share, {:打开 => true, :关闭 => false}, {}, {:class => 'form-control'} %>

                </div>
            </div>    
            <div class="row">
                <div class="cols large-4 l-text-right">
                    <label for="player-name">全屏功能:</label>
                </div>
                <div class="cols large-8">
                    <%= f.check_box :full_screen %>

                </div>
            </div>    
            <script type="text/javascript">
jQuery(document).ready(function($) {
        $('#player_size').on('change', function(e) {
            var optionSelected = $("option:selected", this);
            var valueSelected = this.value;
            var size = valueSelected.split('|');
            var width = parseInt(size[0]);
            var height = parseInt(size[1]);
            $("#player_width").val(width);
            $("#player_height").val(height);
            });
        });
            </script>
            <div class="row">
                <div class="cols large-4 l-text-right">
                    <label for="player-name">长宽:</label>
                </div>
                <div class="cols large-8">
                    <%= select_tag(:player_size, options_for_select(Settings.player.sizes.invert.to_a, "#{@player.width}|#{@player.height}"), {:class => 'form-control player_size'}) %>
                    <%= f.hidden_field :width, :id => 'player_width' %>
                    <%= f.hidden_field :height, :id => 'player_height' %> 
                </div>
            </div>    
            <div class="row form-submit">
                <div class="cols large-8 offset-by-4">
                    <button type="submit" class="btn-success">保存</button>
                    <a data-panel="manage-player" href="javascript:void(0);" class="link-button-cancel btn-show-panel">取消</a>
                </div>
            </div>
        </div>
    </div>

<% end %>
<script type="text/javascript">
// jQuery(document).ready(function($) {
//         videojs("wgcloud_video_1",  {width: '500px'})
//         })
</script>
<!-- <div class="col-md-6">
  <video id="wgcloud_video_1" class="video-js vjs-default-skin vjs-paused vjs-controls-enabled" width="454" controls preload="meta">
    <source src="http://static.smartisanos.cn/common/video/t1-ui.mp4" type='video/mp4'/>

    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
  </video>
  <div class="vjs-big-play-button" role="button" aria-live="polite" tabindex="0" aria-label="play video">
    <span aria-hidden="true"></span>


  </div>
</div>
 -->
    </div>

app/views/players/_nav.html.erb
      <nav class="nav-secondary">
      	<ul class="clearfix">
      		<li class=""><a href="<%= new_player_path  %>"   data-no-turbolink='true' ><i class="fa fa-fw fa-square"></i>新增播放器</a></li>
      		<li><a href="<%= players_path  %>"><i class="fa fa-fw fa-square"></i>播放器管理</a></li>
      		<li class=""><a href="<%= logos_path  %>"><i class="fa fa-fw fa-square"></i>LOGO</a></li>
      		<li><a href="<%= new_logo_path  %>"   data-no-turbolink='true' ><i class="fa fa-fw fa-square"></i>上传LOGO</a></li>
      	</ul>
      </nav>

app/views/players/edit.html.erb
<%=  render 'players/nav' %>

<div id="add-player" class="panel is-current">
            <div class="panel-header clearfix">
            <%= link_to '&lt;&lt; 返回播放器列表'.html_safe, players_path, :class => 'l-right' %> 
            </div>
            <%= render 'form' %>

</div>

app/views/players/index.html.erb
<%=  render 'players/nav' %>

<div id="manage-player" class="panel is-current">
    <div class="panel-header">
        <a href="<%= new_player_path %>" class="link-button-success" data-no-turbolink="true">添加播放器</a>
    </div>
    <div class="panel-content">
        <table summary="播放器列表" class="table">
            <thead>
                <tr>
                    <th>播放器名称</th>
                    <th>创建人</th>
                    <th>创建时间</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
            <% @players.each do |player|  %>
                <tr>
                    <td><%= player.name %></td>
                    <td><%= player.creator && player.creator.nickname %></td>
                    <td><%= player.created_at && player.created_at.strftime("%Y/%m/%d %H:%M") %></td>
                    <td>
                        <%= link_to '预览', player, 'data-no-turbolink' => true %>
                        <%= link_to '修改', edit_player_path(player),  'data-no-turbolink' => true %>
                        <%= link_to '删除', player, method: :delete, data: { confirm: '你确定要删除?' } %>
                    </td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/players/new.html.erb
<%=  render 'players/nav' %>

<div id="add-player" class="panel is-current">
            <div class="panel-header clearfix">
            <%= link_to '&lt;&lt; 返回播放器列表'.html_safe, players_path, :class => 'l-right' %> 
            </div>
            <%= render 'form' %>

</div>

app/views/players/show.html.erb
<% style '/player1/video-js.css' %>
<% style '/player1/videojs.watermark.css' %>
<% javascript '/player1/video.js' %>
<% javascript '/player1/videojs.watermark.js' %>
  <script>
    videojs.options.flash.swf = "/player1/video-js.swf";
  </script>

<%=  render 'players/nav' %>
<div class="tab-panel current" id="add-player">
  <div class="panel-links">
    <%= link_to '&lt;&lt; 返回播放器列表'.html_safe, players_path, :class => 'btn-return-link' %> |
<%= link_to '编辑', edit_player_path(@player),  'data-no-turbolink' => true  %> 

  </div>
  <h3>播放器 <%= @player.name %> 预览</h3>
<%= render 'common/player'  %>    

</div>